import math
import os
import unittest
from unittest.mock import patch

import numpy as np
import pandas as pd
from scipy.integrate import quad

os.environ.setdefault('QT_QPA_PLATFORM', 'offscreen')
os.environ.setdefault('MPLCONFIGDIR', '/tmp/psysummary-test-matplotlib')

from PyQt5.QtWidgets import QApplication, QComboBox, QLineEdit

from app.lib.cognitiveModelDialog import CognitiveModelDialog
from app.cognitiveModelSpec import (
    LBA_MODEL, RATCLIFF_MODEL, RDM_MODEL, cognitive_model_reference_text,
    make_model_specification,
    validate_model_specification,
)
from app.cognitiveModels import (
    _wald_single_pdf, diffusion_cdf, diffusion_pdf, diffusion_quantile,
    fit_cognitive_model, lba_cdf, lba_pdf, lba_quantile, lba_random,
    rdm_cdf, rdm_pdf, rdm_quantile,
)
from app.lib.draggablelistwidget import DraggableListWidget, MODEL_SPEC_ROLE
from app.lib.fitCognitiveModelThread import FitCognitiveModelThread


class CognitiveModelNumericalTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.app = QApplication.instance() or QApplication([])

    def test_diffusion_boundary_densities_sum_to_one(self):
        parameters = dict(a=1.0, v=1.0, t0=0.2, z=0.5, s=1.0)
        lower = quad(lambda value: diffusion_pdf(value, 'lower', **parameters), 0.2, 8.0)[0]
        upper = quad(lambda value: diffusion_pdf(value, 'upper', **parameters), 0.2, 8.0)[0]
        self.assertAlmostEqual(lower + upper, 1.0, places=6)
        self.assertAlmostEqual(upper, 1.0 / (1.0 + math.exp(-1.0)), places=6)

    def test_lba_race_densities_sum_to_one(self):
        parameters = dict(A=0.5, b=1.0, t0=0.2, mean_v=[2.0, 1.0], sd_v=[1.0, 1.0])
        mass = sum(
            quad(lambda value: lba_pdf(value, response, **parameters), 0.2, 10.0, limit=200)[0]
            for response in (1, 2)
        )
        self.assertAlmostEqual(mass, 1.0, places=3)

    def test_lba_and_rdm_match_rtdists_reference_equations(self):
        times = np.array([0.3, 0.5, 1.0])
        expected_lba = np.array([0.014595309951, 2.365578031381, 0.106351748727])
        expected_rdm = np.array([2.050150052311, 1.106841665809, 0.080314304635])
        np.testing.assert_allclose(
            lba_pdf(times, 1, A=0.5, b=1.0, t0=0.2,
                    mean_v=[2.0, 1.0], sd_v=[1.0, 1.0]),
            expected_lba, rtol=1e-10, atol=1e-12)
        np.testing.assert_allclose(
            rdm_pdf(times, 1, A=0.5, b=1.0, t0=0.2, v=[2.0, 1.0]),
            expected_rdm, rtol=1e-10, atol=1e-12)

    def test_models_match_rtdists_0_12_0_reference_grid(self):
        """Compare representative PDF, CDF, and quantile values generated by rtdists."""
        times = np.array([0.3, 0.5, 0.8, 1.2])
        ddm_cases = [
            (
                dict(a=1, v=1, t0=0.2, z=0.4, d=0, sz=0, sv=0, st0=0, s=1),
                {
                    'lower': [1.44574360865521, 0.39794185624245,
                              0.0768298761813114, 0.00873642995425235],
                    'upper': [2.16697119497287, 1.05066735898987,
                              0.208773619004941, 0.0237480569514612],
                },
            ),
            (
                dict(a=1.3, v=-0.7, t0=0.25, z=0.6, d=0.04,
                     sz=0.2, sv=0.5, st0=0.1, s=0.8),
                {
                    'lower': [0.000999314435384243, 1.477045523869939,
                              0.7398166164757115, 0.2706998221561852],
                    'upper': [0.007619822031239648, 0.2984190310594501,
                              0.2003152223105419, 0.08824359330453652],
                },
            ),
        ]
        for parameters, expected_by_response in ddm_cases:
            for response, expected in expected_by_response.items():
                np.testing.assert_allclose(
                    diffusion_pdf(times, response, **parameters), expected,
                    rtol=2e-7, atol=2e-6)

        self.assertAlmostEqual(
            diffusion_cdf(0.8, 'lower', **ddm_cases[0][0]), 0.3490043787490383, places=6)
        self.assertAlmostEqual(
            diffusion_cdf(0.8, 'upper', **ddm_cases[0][0]), 0.5984417143175156, places=6)
        self.assertAlmostEqual(
            diffusion_cdf(0.8, 'lower', **ddm_cases[1][0]), 0.4878444783361123, places=5)
        self.assertAlmostEqual(
            diffusion_cdf(0.8, 'upper', **ddm_cases[1][0]), 0.1120607773498064, places=5)
        self.assertAlmostEqual(
            diffusion_quantile(
                0.25, 'lower', interval=(0, 10), scale_probability=True, **ddm_cases[0][0]),
            0.272685749066332, delta=4e-4)
        self.assertAlmostEqual(
            diffusion_quantile(
                0.25, 'upper', interval=(0, 10), scale_probability=True, **ddm_cases[0][0]),
            0.326229266143871, delta=4e-4)

        race_cases = [
            (
                lba_pdf, lba_cdf, lba_quantile,
                dict(A=0.5, b=1, t0=0.2, mean_v=[2, 1], sd_v=[1, 1], st0=0),
                {
                    1: [0.014595309950927, 2.36557803138125,
                        0.340573888763559, 0.0422215572069633],
                    2: [0.000393390520297204, 0.847514712927402,
                        0.19829759899821, 0.0299886741090591],
                },
                {1: 0.653348024084254, 2: 0.234807610280719},
                {1: 0.443828976450131, 2: 0.482696283868811},
            ),
            (
                rdm_pdf, rdm_cdf, rdm_quantile,
                dict(A=0.5, b=1, t0=0.2, v=[2, 1], s=1, st0=0),
                {
                    1: [2.05015005231053, 1.10684166580932,
                        0.216585178372412, 0.0319635581779654],
                    2: [1.17225895712821, 0.578500227320573,
                        0.103062762327004, 0.0139334573815304],
                },
                {1: 0.606165514918286, 2: 0.327912097097907},
                {1: 0.333957945278325, 2: 0.328692288397977},
            ),
        ]
        for pdf, cdf, quantile, parameters, expected_pdf, expected_cdf, expected_quantile in race_cases:
            for response in (1, 2):
                np.testing.assert_allclose(
                    pdf(times, response, **parameters), expected_pdf[response],
                    rtol=2e-9, atol=1e-11)
                self.assertAlmostEqual(
                    cdf(0.8, response, **parameters), expected_cdf[response], places=6)
                self.assertAlmostEqual(
                    quantile(
                        0.25, response, interval=(0, 10),
                        scale_probability=True, **parameters),
                    expected_quantile[response], places=6)

    def test_rdm_matches_published_fixed_start_wald_density(self):
        rt = np.array([0.1, 0.3, 0.8, 1.5])
        b = 1.0
        v = 2.0
        expected = b * (2.0 * math.pi * rt ** 3) ** -0.5 * np.exp(
            -((v * rt - b) ** 2) / (2.0 * rt))
        np.testing.assert_allclose(_wald_single_pdf(rt, 0.0, b, v, 1.0), expected, rtol=1e-10)

    def test_rdm_race_densities_sum_to_one(self):
        parameters = dict(A=0.4, b=1.0, t0=0.25, v=[2.5, 1.5], s=1.0)
        mass = sum(
            quad(lambda value: rdm_pdf(value, response, **parameters), 0.25, 10.0, limit=200)[0]
            for response in (1, 2)
        )
        self.assertAlmostEqual(mass, 1.0, places=4)

    def test_all_fixed_model_evaluates_without_optimizer(self):
        dataframe = pd.DataFrame({
            'rt': [0.36, 0.42, 0.50, 0.61, 0.39, 0.55],
            'choice': ['left', 'right', 'right', 'left', 'right', 'left'],
            'correct': [1, 1, 0, 1, 1, 0],
        })
        specification = make_model_specification(
            RATCLIFF_MODEL, 'rt', 'choice', ['left', 'right'], minimum_rt=0.36,
            accuracy_variable='correct')
        specification['optimizer']['seed'] = 73
        specification['response_mapping'] = {'left': 'upper', 'right': 'lower'}
        for parameter in specification['parameters']:
            parameter['mode'] = 'fixed'
        fit = fit_cognitive_model(dataframe, specification)
        self.assertTrue(fit['converged'])
        self.assertIn('without optimization', fit['message'])
        self.assertEqual(fit['response_counts'], {'left': 3, 'right': 3})
        np.testing.assert_array_equal(fit['accuracy'], [1, 1, 0, 1, 1, 0])
        self.assertAlmostEqual(fit['accuracy_rate'], 4 / 6)
        self.assertEqual(fit['random_seed'], 73)
        self.assertAlmostEqual(fit['log_likelihood'], 0.6159870928231193, places=8)

    def test_constrained_optimizer_moves_from_a_nonoptimal_start(self):
        dataframe = lba_random(
            250, A=0.5, b=1.0, t0=0.2,
            mean_v=[2.0, 1.0], sd_v=[1.0, 1.0], random_state=8102)
        specification = make_model_specification(
            LBA_MODEL, 'rt', 'response', [1, 2], minimum_rt=dataframe['rt'].min())
        for parameter in specification['parameters']:
            parameter['mode'] = 'fixed'
            if parameter['name'] in {'A', 'b', 't0', 'mean_v[1]', 'mean_v[2]'}:
                parameter['mode'] = 'free'
        initial = {
            parameter['name']: parameter['value'] for parameter in specification['parameters']
        }
        specification['optimizer'].update(starts=1, seed=73, max_iterations=1000)
        fit = fit_cognitive_model(dataframe, specification)
        fitted = dict(zip(fit['parameter_names'], fit['parameters']))
        self.assertTrue(fit['converged'])
        self.assertEqual(fit['optimizer_method'], 'SLSQP')
        self.assertGreater(
            max(abs(fitted[name] - initial[name])
                for name in ('A', 'b', 't0', 'mean_v[1]', 'mean_v[2]')),
            0.01,
        )

    def test_identifiability_constraints_are_enforced(self):
        specification = make_model_specification(
            RDM_MODEL, 'rt', 'choice', [1, 2], minimum_rt=0.3)
        next(parameter for parameter in specification['parameters'] if parameter['name'] == 's')['mode'] = 'free'
        with self.assertRaisesRegex(ValueError, 'must be Fixed'):
            validate_model_specification(specification, ['rt', 'choice'])

        specification = make_model_specification(
            LBA_MODEL, 'rt', 'choice', [1, 2], minimum_rt=0.3)
        for parameter in specification['parameters']:
            if parameter['name'].startswith('sd_v['):
                parameter['mode'] = 'free'
        with self.assertRaisesRegex(ValueError, 'At least one LBA sd_v'):
            validate_model_specification(specification, ['rt', 'choice'])

        specification = make_model_specification(
            LBA_MODEL, 'rt', 'choice', [1, 2], minimum_rt=0.3)
        invalid_sd = next(parameter for parameter in specification['parameters']
                          if parameter['name'] == 'sd_v[1]')
        invalid_sd.update(value=0, lower=-1)
        with self.assertRaisesRegex(ValueError, 'standard deviations must be greater than zero'):
            validate_model_specification(specification, ['rt', 'choice'])

        specification = make_model_specification(
            RDM_MODEL, 'rt', 'choice', [1, 2], minimum_rt=0.3)
        invalid_scale = next(parameter for parameter in specification['parameters']
                             if parameter['name'] == 's')
        invalid_scale.update(value=0, lower=-1)
        with self.assertRaisesRegex(ValueError, 'diffusion scale s must be greater than zero'):
            validate_model_specification(specification, ['rt', 'choice'])

    def test_model_reference_output_identifies_paper_package_and_runtime(self):
        expected_dois = {
            RATCLIFF_MODEL: '10.1162/neco.2008.12-06-420',
            LBA_MODEL: '10.1016/j.cogpsych.2007.12.002',
            RDM_MODEL: '10.3758/s13423-020-01719-6',
        }
        for model, doi in expected_dois.items():
            reference = cognitive_model_reference_text(model)
            self.assertIn(doi, reference)
            self.assertIn('rtdists', reference)
            self.assertIn('0.12-0', reference)
            self.assertIn('not invoked at runtime', reference)
            self.assertIn('SLSQP', reference)

    def test_fit_worker_emits_model_reference_once_per_analysis(self):
        dataframe = pd.DataFrame({
            'rt': [0.35, 0.42, 0.51, 0.63],
            'choice': ['left', 'right', 'left', 'right'],
        })
        specification = make_model_specification(
            RATCLIFF_MODEL, 'rt', 'choice', ['left', 'right'], minimum_rt=0.35)
        for parameter in specification['parameters']:
            parameter['mode'] = 'fixed'
        messages = []
        worker = FitCognitiveModelThread(dataframe, specification, [], [])
        worker.fitStatus.connect(
            lambda _level, message, _show_time: messages.append(message))
        worker._process_model()
        reference_messages = [
            message for message in messages if message.startswith('Model reference:')
        ]
        self.assertEqual(len(reference_messages), 1)
        self.assertIn('10.1162/neco.2008.12-06-420', reference_messages[0])

    def test_dialog_collects_structured_variable_and_parameter_settings(self):
        dataframe = pd.DataFrame({
            'rt': [300, 420, 510, 610],
            'choice': ['left', 'right', 'left', 'right'],
            'correct': [1, 1, 0, 1],
        })
        dialog = CognitiveModelDialog(dataframe, RATCLIFF_MODEL, 'rt')
        self.assertEqual(dialog.response_combo.currentText(), dialog.NONE_LABEL)
        self.assertEqual(dialog.parameter_table.rowCount(), 0)
        self.assertEqual(dialog.seed_spin.value(), 0)
        self.assertEqual(dialog.seed_spin.text(), 'Time-based')
        dialog.response_combo.setCurrentText('choice')
        dialog.accuracy_combo.setCurrentText('correct')
        specification = dialog.specification()
        mapping_row_height = dialog.mapping_table.verticalHeader().defaultSectionSize()
        parameter_row_height = dialog.parameter_table.verticalHeader().defaultSectionSize()
        self.assertLess(dialog.mapping_table.height(), mapping_row_height * 3.5)
        self.assertGreaterEqual(dialog.parameter_table.height(), parameter_row_height * 9)
        dialog.close()
        self.assertEqual(specification['rt_unit'], 'milliseconds')
        self.assertEqual(specification['response_variable'], 'choice')
        self.assertEqual(specification['accuracy_variable'], 'correct')
        self.assertEqual(specification['response_mapping'], {'left': 'lower', 'right': 'upper'})
        self.assertIsNone(specification['optimizer']['seed'])
        self.assertTrue(all({'name', 'mode', 'value', 'lower', 'upper'} <= set(parameter)
                            for parameter in specification['parameters']))
        for row in range(dialog.parameter_table.rowCount()):
            self.assertTrue(dialog.parameter_table.item(row, 0).toolTip())
            for column in range(1, 5):
                self.assertTrue(dialog.parameter_table.cellWidget(row, column).toolTip())

    def test_data_item_model_settings_round_trip_independently_of_display_text(self):
        specification = make_model_specification(
            RATCLIFF_MODEL, 'rt', 'choice', ['left', 'right'], minimum_rt=0.3)
        widget = DraggableListWidget(DraggableListWidget.DataType)
        display_text = f'rt@{RATCLIFF_MODEL}'
        widget.addItem(display_text)
        widget.contentList.append(display_text)
        widget.item(0).setData(MODEL_SPEC_ROLE, specification)
        saved = widget.modelSpecifications()

        widget.item(0).setData(MODEL_SPEC_ROLE, None)
        widget.restoreModelSpecifications(saved)
        self.assertEqual(widget.item(0).text(), display_text)
        self.assertEqual(widget.item(0).data(MODEL_SPEC_ROLE), specification)
        widget.close()

    def test_data_item_context_menu_keeps_model_settings_visible_but_conditional(self):
        widget = DraggableListWidget(DraggableListWidget.DataType)
        widget.addItem('rt@Mean')
        plain_menu = widget._create_data_context_menu(widget.item(0))
        plain_actions = {action.text(): action for action in plain_menu.actions()}
        self.assertTrue(plain_actions['Change Analysis...'].isEnabled())
        self.assertFalse(plain_actions['Model Settings...'].isEnabled())

        widget.item(0).setText(f'rt@{LBA_MODEL}')
        model_menu = widget._create_data_context_menu(widget.item(0))
        model_actions = {action.text(): action for action in model_menu.actions()}
        self.assertTrue(model_actions['Change Analysis...'].isEnabled())
        self.assertTrue(model_actions['Model Settings...'].isEnabled())
        widget.close()

    def test_model_dialog_receives_current_filtered_rows(self):
        dataframe = pd.DataFrame({
            'rt': [0.3, 0.4, 0.5],
            'choice': ['left', 'right', 'unused'],
        })
        filtered = dataframe.iloc[:2].copy()
        specification = make_model_specification(
            RATCLIFF_MODEL, 'rt', 'choice', ['left', 'right'], minimum_rt=0.3)
        widget = DraggableListWidget(DraggableListWidget.DataType)
        display_text = f'rt@{RATCLIFF_MODEL}'
        widget.addItem(display_text)
        widget.setModelContext(dataframe, lambda: filtered)
        received = {}

        def fake_editor(model_dataframe, model, rt_variable, current_specification, parent):
            received['dataframe'] = model_dataframe
            received['model'] = model
            received['rt_variable'] = rt_variable
            return specification

        with patch(
                'app.lib.draggablelistwidget.edit_cognitive_model',
                side_effect=fake_editor):
            self.assertTrue(widget._configure_model_item(widget.item(0), RATCLIFF_MODEL))

        pd.testing.assert_frame_equal(received['dataframe'], filtered)
        self.assertEqual(received['model'], RATCLIFF_MODEL)
        self.assertEqual(received['rt_variable'], 'rt')
        widget.close()

    def test_switching_models_does_not_reuse_previous_model_parameters(self):
        dataframe = pd.DataFrame({
            'rt': [0.3, 0.4, 0.5, 0.6],
            'choice': ['left', 'right', 'left', 'right'],
        })
        previous_specification = make_model_specification(
            RATCLIFF_MODEL, 'rt', 'choice', ['left', 'right'], minimum_rt=0.3)
        widget = DraggableListWidget(DraggableListWidget.DataType)
        widget.addItem(f'rt@{RATCLIFF_MODEL}')
        widget.item(0).setData(MODEL_SPEC_ROLE, previous_specification)
        widget.setModelContext(dataframe)
        received = {}

        def fake_editor(model_dataframe, model, rt_variable, specification, parent):
            received['model'] = model
            received['specification'] = specification
            return make_model_specification(
                LBA_MODEL, rt_variable, 'choice', ['left', 'right'], minimum_rt=0.3)

        with patch(
                'app.lib.draggablelistwidget.edit_cognitive_model',
                side_effect=fake_editor):
            self.assertTrue(widget._configure_model_item(widget.item(0), LBA_MODEL))

        self.assertEqual(received['model'], LBA_MODEL)
        self.assertIsNone(received['specification'])
        widget.close()

        dialog = CognitiveModelDialog(
            dataframe, LBA_MODEL, 'rt', previous_specification)
        self.assertEqual(dialog.response_combo.currentText(), dialog.NONE_LABEL)
        self.assertEqual(dialog.parameter_table.rowCount(), 0)
        dialog.response_combo.setCurrentText('choice')
        parameter_names = [
            dialog.parameter_table.item(row, 0).text()
            for row in range(dialog.parameter_table.rowCount())
        ]
        self.assertEqual(parameter_names[:4], ['A', 'b', 't0', 'st0'])
        self.assertIn('mean_v[1]', parameter_names)
        self.assertNotIn('z', parameter_names)
        dialog.close()

    def test_reopened_dialog_does_not_overlay_stale_table_editors(self):
        dataframe = pd.DataFrame({
            'rt': [0.3, 0.4, 0.5, 0.6],
            'choice': [6.0, 5.0, 6.0, 5.0],
            'correct': [1, 1, 0, 1],
        })
        first_dialog = CognitiveModelDialog(dataframe, RATCLIFF_MODEL, 'rt')
        first_dialog.response_combo.setCurrentText('choice')
        first_dialog.accuracy_combo.setCurrentText('correct')
        specification = first_dialog.specification()
        first_dialog.close()

        reopened = CognitiveModelDialog(
            dataframe, RATCLIFF_MODEL, 'rt', specification)
        reopened.show()
        self.app.processEvents()
        visible_mapping_combos = [
            widget for widget in reopened.mapping_table.findChildren(QComboBox)
            if widget.isVisibleTo(reopened.mapping_table)
        ]
        visible_parameter_combos = [
            widget for widget in reopened.parameter_table.findChildren(QComboBox)
            if widget.isVisibleTo(reopened.parameter_table)
        ]
        visible_parameter_edits = [
            widget for widget in reopened.parameter_table.findChildren(QLineEdit)
            if widget.isVisibleTo(reopened.parameter_table)
        ]
        self.assertEqual(reopened.mapping_table.item(0, 0).text(), '6.0')
        self.assertEqual(reopened.parameter_table.item(0, 0).text(), 'a')
        self.assertEqual(len(visible_mapping_combos), 2)
        self.assertEqual(len(visible_parameter_combos), 9)
        self.assertEqual(len(visible_parameter_edits), 27)
        reopened.close()

    def test_reopened_dialog_removes_response_levels_excluded_by_filters(self):
        complete_data = pd.DataFrame({
            'rt': [0.3, 0.4, 0.5],
            'choice': ['left', 'right', 'unused'],
        })
        specification = make_model_specification(
            LBA_MODEL, 'rt', 'choice', ['left', 'right', 'unused'], minimum_rt=0.3)
        filtered_data = complete_data.iloc[:2].copy()
        dialog = CognitiveModelDialog(
            filtered_data, LBA_MODEL, 'rt', specification)
        self.assertEqual(
            [dialog.mapping_table.item(row, 0).text() for row in range(dialog.mapping_table.rowCount())],
            ['left', 'right'],
        )
        self.assertEqual(dialog.parameter_table.rowCount(), 8)
        dialog.close()


if __name__ == '__main__':
    unittest.main()
